### PR TITLE
Create eo.properties

### PR DESCRIPTION
**Pull request by Airon90**
Added Esperanto localization

### CODE REVIEW

**Comment by Flaburgan** [comment]
Esperanto doesn't have a translation in the [manifest file](https://github.com/Flaburgan/diaspora-webapp/blob/master/manifest.webapp), could you please add it there too?

**Comment by Flaburgan** [comment]
Oh sorry, didn't see your first PR.

**Comment by Airon90** [comment]
Don't worry ;)

**Comment by Flaburgan** [comment]
Thanks!

**Pull request merged**
